branch-defaults:
  default:
    environment: djangoproj
    group_suffix: null
global:
  application_name: twitt
  branch: null
  default_ec2_keyname: null
  default_platform: python2.7
  default_region: us-east-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
